### PR TITLE
Feature: UIowa book

### PR DESCRIPTION
**Pull request by mark-bennett-uiowa**
1. git checkout feature_uiowa_book
2. composer install
3. drush @theming.local si collegiate_basic
4. Check that you can create a book page content item.
5. Check that you can create a book outline structure and have that hierarchy show up properly under the Table of Contents page.

### CODE REVIEW

**Comment by pyrello** [comment]
A couple questions after testing:
* Should the tags be implemented as the comma separated autocomplete option?
* Is it correct that the Table of Contents block should only show items below the top page?

**Comment by mark-bennett-uiowa** [comment]
Tags were changed based off a suggestion by another developer. Does not matter to me. Can be changed back.

Table of Contents PAGE will show all depths (up to the max 9 the book module has). The Table of Contents BLOCK will only show depth level 1 nodes for simplicity (and that is how the UI Ops Manual does it too). It is supposed to provide quick links to the highest level headings of that book.

**Comment by mark-bennett-uiowa** [comment]
This module is setup specifically for one book per site. Additional books can be created, but will cause confusion in the ToC block/page. Neither view has a restriction on WHAT book it is showing results from. This was added and removed during development for various reasons. If this module is to be used on a site with multiple books (manuals) then changes need to be made on that site.

**Comment by pyrello** [comment]
So, is the intention of this module to only be used for single book sites like the policy site you are setting up? If so, I think it should be named something a little bit more descriptive.

**Comment by mark-bennett-uiowa** [comment]
No, not necessarily, it can handle multiple books. But the Tables of Contents do not show the top level book, only children, children of children, and so forth. The views need to be slightly tweaked if this is to be used on a site with multiple books. Im curious to know what sites we are going to have on campus currently that would have multiple books anyways.

**Comment by pyrello** [comment]
I use multiple books on the Grad College site.

I don't think you would want to TOC to display multiple top-level books. The way it is set up makes sense to me now. I guess it would maybe be nice to have the TOC have some sort of contextual filter to allow it to show a TOC based on the book it was in the context of.

**Comment by mark-bennett-uiowa** [comment]
Definitely. Im all for the contextual filter. Lets add that as an update for the near future.

**Pull request merged**
