### PR TITLE
Feature: Layout Builder patch for form blocks

### PR DESCRIPTION
**Pull request by bspeare**
Added lb patch for #217.

# How to test

1. `composer install`
2. `drush @theming.local si collegitate`
3.  Create a page
4.  Edit layout and add search form block
5. Save page and edit and re-save page mulitple times

### CODE REVIEW

**Comment by pyrello** [comment]
I tested this and it seemed to work.

I also tested enabling the `uiowa_book` module and adding the exposed form that provides to the page via layout builder, which also worked.

Then I tried moving the block between sections and saving it and I am getting the "Unsaved changes" message again:

Screen Shot 2020-01-10 at 12 26 07 PM

It doesn't seem to disable the ability to save in the same way, but it still seems not quite right.

**Comment by bspeare** [comment]
@pyrello I'll try some of the other patches and trash this if none of them work.  Thanks!

**Comment by pyrello** [comment]
I'm also seeing the following errors in the log:
```
Notice: Undefined variable: view_display in Drupal\layout_builder_restrictions\Plugin\LayoutBuilderRestriction\EntityViewModeRestriction->getValuefromSectionStorage() (line 157 of /var/www/uiowa01/docroot/modules/contrib/layout_builder_restrictions/src/Traits/PluginHelperTrait.php)
```

```
InvalidArgumentException: Invalid UUID "content" in Drupal\layout_builder\Section->getComponent() (line 177 of /var/www/uiowa01/docroot/core/modules/layout_builder/src/Section.php).
```

**Comment by bspeare** [comment]
@pyrello , so the patch works but it just shows the "unsaved changes" message after saving the node - correct?   And it also spits out a bunch of php errors?

**Comment by pyrello** [comment]
That seems to be the case, yes. I'm going to run an install without the patch to see if the errors are caused by it or already exist without it.

**Comment by pyrello** [comment]
Both of those errors seems to be unrelated.

I think this patch is an improvement on where we are at now, so we should incorporate it. @mark-bennett-uiowa This is your heads up that when you see the "Unsaved changes" message you should be able to ignore it.

**Comment by mark-bennett-uiowa** [comment]
Sounds good. Opened up another issue #318 about this, so hopefully this fix will take care of that. Thanks all.

**Pull request merged**
