### PR TITLE
Feature: Drupal 8.8.x + media embed updates + final Lightning removal

### PR DESCRIPTION
**Pull request by pyrello**
This update moves the project to drupal/core 8.8.x along with related dependency updates for acquia/blt and drupal/pathauto. Unnecessary config was removed from media modules.

# Testing...
Since this was a minor version core update, it would be good to give all the main things we have been working on a shake to make sure we didn't knock anything loose. Below I will detail the specific items that have changed.
1. Test core <drupal-media> embed. It should allow for all types of media to be embedded
2. Add a page and click the Layout Builder Tab
3. Add a uiowa block with media field
4. Add media and verify that #205 looks better
5. Verify that basic block is no longer an option

### CODE REVIEW

**Comment by pyrello** [comment]
@bspeare @mark-bennett-uiowa Any updates on testing this? I have tested a number of scenarios and I am pretty comfortable with it, so please let me know if you are ready to pass it.

**Comment by mark-bennett-uiowa** [comment]
Just leaving some tracking of the issues I have run into:
git checkout feature_drupal_8_8_x
git pull
composer install

Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/2018-10-12/1356276-531.patch

                                                                                                                                                                                 
  [Exception]                                                                                                                                                                    
  Cannot apply patch 1356276 - Allow profiles to define a base/parent profile and load them in the correct order (https://www.drupal.org/files/issues/2018-10-12/1356276-531.pa  
  tch)!                                                                                                                                                                          

Ran composer install again and it worked.

**Comment by mark-bennett-uiowa** [comment]
Ran **drush @theming.local si collegiate_basic**

Terminated with the following error:
` [notice] Starting Drupal installation. This takes a while.
TypeError: Argument 7 passed to Drupal\Core\Config\ConfigInstaller::__construct() must be an instance of Drupal\Core\Config\ProfileExtensionList or null, instance of Drupal\Core\Extension\ProfileExtensionList given, called in /var/www/uiowa01/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php on line 293 in /var/www/uiowa01/docroot/core/lib/Drupal/Core/Config/ConfigInstaller.php on line 93 #0 /var/www/uiowa01/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php(293): Drupal\Core\Config\ConfigInstaller->__construct(Object(Drupal\Core\Config\ConfigFactory), Object(Drupal\Core\Config\CachedStorage), Object(Drupal\Core\Config\TypedConfigManager), Object(Drupal\Core\Config\ConfigManager), Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher), 'collegiate_basi...', Object(Drupal\Core\Extension\ProfileExtensionList))
#1 /var/www/uiowa01/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\Component\DependencyInjection\Container->createService(Array, 'drupal.proxy_or...')
#2 /var/www/uiowa01/docroot/core/lib/Drupal/Core/ProxyClass/Config/ConfigInstaller.php(64): Drupal\Component\DependencyInjection\Container->get('drupal.proxy_or...')
#3 /var/www/uiowa01/docroot/core/lib/Drupal/Core/ProxyClass/Config/ConfigInstaller.php(75): Drupal\Core\ProxyClass\Config\ConfigInstaller->lazyLoadItself()
#4 /var/www/uiowa01/docroot/core/includes/install.inc(655): Drupal\Core\ProxyClass\Config\ConfigInstaller->installDefaultConfig('core', 'core')
#5 /var/www/uiowa01/docroot/core/includes/install.core.inc(1107): drupal_install_system(Array)
#6 /var/www/uiowa01/docroot/core/includes/install.core.inc(709): install_base_system(Array)
#7 /var/www/uiowa01/docroot/core/includes/install.core.inc(584): install_run_task(Array, Array)
#8 /var/www/uiowa01/docroot/core/includes/install.core.inc(117): install_run_tasks(Array, NULL)
#9 /var/www/uiowa01/vendor/drush/drush/includes/drush.inc(196): install_drupal(Object(Composer\Autoload\ClassLoader), Array)
#10 /var/www/uiowa01/vendor/drush/drush/includes/drush.inc(181): drush_call_user_func_array('install_drupal', Array)
#11 /var/www/uiowa01/vendor/drush/drush/src/Commands/core/SiteInstallCommands.php(148): drush_op('install_drupal', Object(Composer\Autoload\ClassLoader), Array)
#12 [internal function]: Drush\Commands\core\SiteInstallCommands->install('collegiate_basi...', Array)
#13 /var/www/uiowa01/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
#14 /var/www/uiowa01/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#15 /var/www/uiowa01/vendor/consolidation/annotated-command/src/CommandProcessor.php(178): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#16 /var/www/uiowa01/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(302): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#17 /var/www/uiowa01/vendor/symfony/console/Command/Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/uiowa01/vendor/symfony/console/Application.php(1000): Symfony\Component\Console\Command\Command->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/uiowa01/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/uiowa01/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/uiowa01/vendor/drush/drush/src/Runtime/Runtime.php(118): Symfony\Component\Console\Application->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/uiowa01/vendor/drush/drush/src/Runtime/Runtime.php(49): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/uiowa01/vendor/drush/drush/drush.php(72): Drush\Runtime\Runtime->run(Array)
#24 /var/www/uiowa01/vendor/drush/drush/includes/preflight.inc(18): require('/var/www/uiowa0...')
#25 phar:///usr/local/bin/drush/bin/drush.php(141): drush_main()
#26 /usr/local/bin/drush(10): require('phar:///usr/loc...')
#27 {main}
TypeError: Argument 7 passed to Drupal\Core\Config\ConfigInstaller::__construct() must be an instance of Drupal\Core\Config\ProfileExtensionList or null, instance of Drupal\Core\Extension\ProfileExtensionList given, called in /var/www/uiowa01/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php on line 293 in Drupal\Core\Config\ConfigInstaller->__construct() (line 93 of /var/www/uiowa01/docroot/core/lib/Drupal/Core/Config/ConfigInstaller.php).
 [warning] Drush command terminated abnormally. Check for an exit() in your Drupal site.`

**Comment by mark-bennett-uiowa** [comment]
After breaking my install, and getting a php version warning, I upgraded from 7.1 to 7.3 via Homebrew and for good measure (or ignorance) `curl -s http://php-osx.liip.ch/install.sh | bash -s 7.3`. Reran a **composer install** from the uiowa01 directory succesfully and then was able to run **drush @theming.local si collegiate_basic** successfully with zero errors. Resuming testing now.

**Comment by mark-bennett-uiowa** [comment]
Tested the following bullet points:

1. Test core embed. It should allow for all types of media to be embedded
- Created a new /home page. Added lorem text and created three new media entities (1 image, 1 document, and 1 remote video). Did NOT test video as I did not have a video file to test at the time. Inserted each of the entities in amongst the lorem text. All three were successful. Mildly concerned with the display of the document embed. Can we clean this up?
Screen Shot 2019-11-21 at 4 00 58 PM

2. Add a page and click the Layout Builder Tab
- Created a new homepage as I have before for the policy site example.
3. Add a uiowa block with media field
- Added a new section and a new UIowa Feature block. Added Image to the block.
4. Add media and verify that #205 looks better
-  Block successfully added with media image. #205 looks MUCH better. See images below:
Screen Shot 2019-11-21 at 3 46 44 PM
Screen Shot 2019-11-21 at 3 47 04 PM
FURTHER NOTES:
--Remove button still incorrect from #219 .
--Update widget button still showing. 
--Insert selected button has bold text by default and thin, non-boldened text on mouseover:
Screen Shot 2019-11-21 at 3 49 54 PM
Screen Shot 2019-11-21 at 3 49 59 PM

5. Verify that basic block is no longer an option
- Verified that the Basic Block option is no longer available.

**Comment by pyrello** [comment]
@mark-bennett-uiowa I'm kind of curious where that button styling comes from. It doesn't look like the button styling from our frontend theme.

I think all your outstanding concerns are represented by existing issues now, no?

**Comment by mark-bennett-uiowa** [comment]
@pyrello yep! Thanks for adding those. I would assume the button styling is nested within the media module somewhere. Do you see the same styling on your end? If so, we may need to create an issue and make those updates in the theme.

**Pull request merged**
