### PR TITLE
Feature: Layout builder direct add button

### PR DESCRIPTION
**Pull request by pyrello**

### CODE REVIEW

**Comment by pyrello** [comment]
@bspeare When you say you are unable to add a custom block, do you mean to a content item through Layout Builder?

**Comment by bspeare** [comment]
Yes, the button brings up the custom block but there are Ajax errors when I try to use the "Add Block" button in the tray.

**Comment by pyrello** [comment]
Okay. I'll take a look

**Comment by pyrello** [comment]
I created an issue for this in the lb_direct_add module issue queue: https://www.drupal.org/project/lb_direct_add/issues/3083722

**Comment by pyrello** [comment]
I have updated the lb_direct_add module and I believe this is fixed. This feature branch is updated with the most recent version of that module.

To test, pull the changes for this branch, then run `composer install`

**Pull request merged**
