### PR TITLE
Feature multisite adaptations

### PR DESCRIPTION
**Pull request by pyrello**

### CODE REVIEW

**Comment by pyrello** [comment]
To test, you'll need to go through the list at #18 and validate that each item works.

The command for testing (inside Drupal VM) is:
```
blt uiowa:multisite
// or
blt uisite
```

You should be able to follow the prompts to test that all the required things happen. I have tested a fair amount, but it would be good to try out a variety of different scenarios as you are able to think of them and to document any edge cases you try out.

If you need more information, please let me know.

**Comment by bspeare** [comment]
@pyrello I made it to "Would you like to generate new virtual host entry" and entered "yes" and got a PHP Fatal error: `Uncaught Error: Class 'Acquia\Blt\Robo\Common\YamlWriter' not found in /var/www/uiowa01/blt/src/Blt/Plugin/Commands/MultisiteCommands.php:245`.  Have you seen that before?

**Comment by pyrello** [comment]
@bspeare This isn't happening when I run it. Is it possible that you need to run `composer install` to update BLT?

**Comment by bspeare** [comment]
That's probably it, thanks.

**Comment by pyrello** [comment]
@bspeare Oops! I forgot to include the instructions for setting up the Acquia Cloud API credentials.

It is necessary to create a `blt/local.blt.yml` file and include the following:
```
credentials:
  acquia:
    key: {key}
    secret: {secret}
```
You may already have a `blt/local.blt.yml` file if you have started using Drupal VM. The {key} and {secret} values are created by visiting this page: https://cloud.acquia.com/a/profile/tokens

If you have already created these credentials and stored them somewhere, you can use the existing ones. Otherwise it is no big deal to create a new one.

__Note: The above file _does not_ get added to version control. It should be ignored by git.__

**Comment by pyrello** [comment]
This branch is ready for review again. @bspeare @mark-bennett-uiowa

**Comment by pyrello** [comment]
Things to test:
* Whether you can make it through the whole process without issue. Go through a few times and try answering yes/no to different questions.
* That it will properly handle not attempting to create a database that already exists. Use 'tester' or 'tester.uiowa.edu' as the initial input.
* Shows message to run `vagrant provision`.
* That you can run drush commands using the alias for the created site inside Drupal VM.
* That the local domain that is added to box/config.yml is the same as what is added to sites.php.
* Any other scenarios you can think of.

**Comment by pyrello** [comment]
I have tested that the site install command runs now. There may be some other issues with different permutations of options, but I think this is largely working and functional now. I propose that we go ahead and merge this branch and we can open up any additional issues that are needed to fine tune it over time.

**Comment by bspeare** [comment]
Sounds good.  I just tested it and it worked for me.

**Pull request merged**
