### PR TITLE
Feature: Collegiate theme updates

### PR DESCRIPTION
**Pull request by bspeare**
This feature branch addresses issues #188, #163, #162, #156,  #135, #191 

# Testing

#188    

1. drush @theming.local si collegiate_basic
2. Add basic page content item with lots of body text
3. Visit the page to see if body content width is set to 74.75% of page width
4. You might need to refresh the page after saving the page
5. Also edit using layout builder and add a "Basic Text" block to a one-column layout with lots of text. 
6. Save the page and verify that the content width for that text block is set to 74.75%. 

#163

1. drush @theming.local si collegiate_basic
2. Add basic page content item
3. Visit the page and edit using layout builder
4. Add 1, 2, 3 column layout sections and add content
5. Verify that the width you have set in the theme settings is being used on each layout
6. Adjust layout section width settings to full or fixed container to override the theme settings

Screen Shot 2019-11-07 at 3 18 20 PM

#162

1. drush @theming.local si collegiate_basic
2. Create a view
3. Verify that view page width reflects the width selected in theme settings
4. You might not see a page title because of #187 

#135 

1. drush @theming.local si collegiate_basic
2. Create a basic page
3. In a new browser, verify that the page title and breadcrumbs have spacing
4. Enable entity_types_news content type and create a news item
5. In a new browser, verify that there is a enough space above and below the content 
6. You might not see the breadcrumbs or page title because of issue #186

#156

1. drush @theming.local si collegiate_basic
2. Add basic page content item
3. Visit the page and edit using layout builder
4. Add 1, 2, 3 column layout sections and add custom blocks to each layout
5. Save the page and verify that there is an equal amount of spacing between each column

#191 

1. Verify that the default installation without a site slogan has reduced spacing between the wordmark and the site name. 
2. Add a site slogan to test whether extra spacing is added back. 
3. Change the background color to gold in the theme settings to test whether the spacing between the wordmark and the site name expands. 

Screen Shot 2019-11-08 at 2 56 29 PM

Screen Shot 2019-11-08 at 2 56 55 PM

#190 

1. Verify with AInspector WCAG toolbar that theme does not have any violations.

Screen Shot 2019-11-11 at 1 56 28 PM

### CODE REVIEW

**Comment by mark-bennett-uiowa** [comment]
#188 
Created a basic page and added 10 paragraphs of text. Block width was set to 74.75% (block class is block-field-blocknodepagebody). Did not need to refresh page to see proper width setting.
Added a new section to the page below the default section. Added a large amount of text. Kept default settings and saved section and block. Block width is also set properly to 74.75% (block class is block-inline-blockbasic). Did run into visual issues shown below
Screen Shot 2019-11-08 at 1 26 19 PM
Screen Shot 2019-11-08 at 1 51 58 PM

#163 
This seems to be working for all the tests.

#162 
Create an empty view and gave it a header with a large amount of text. Verified full width. Does not display page title (as noted above).

**Comment by mark-bennett-uiowa** [comment]
#135 
This appears to be working correctly. I have proper page width and margins/padding at the top and bottom of page. Both Chrome and Safari appear correct. When page is shrunk to a smaller width (for portable devices) it doesn't appear that there is any padding on the sides of the page however.

#156 
Used same content from test for #163 above and verified that there is equal spacing between each column. Changed column widths to several different settings and still worked properly.

**Comment by mark-bennett-uiowa** [comment]
Passed tests except for small visual issues mentioned above.

**Comment by pyrello** [comment]
@bspeare Why is the body text set to 74.75%

**Comment by bspeare** [comment]
@pyrello The body text issue is here: https://github.com/uiowa/uiowa01/issues/188.

**Comment by pyrello** [comment]
I'm doing the testing related to #163 and it appears as though there is no outer margin when the theme setting is set to full width.

Here are screenshots:
Screen Shot 2019-11-11 at 2 43 31 PM
Screen Shot 2019-11-11 at 2 43 47 PM
Screen Shot 2019-11-11 at 2 44 01 PM

I don't know that these really do justice to what I am seeing, since the comment format here adds some padding and the images have white backgrounds. Suffice it to say that the text goes all the way to the edges of the screen.

Steps to reproduce
1. drush @theming.local si collegiate_basic
2. Add basic page content item
3. Visit the page and edit using layout builder
4. Add 1, 2, 3 column layout sections and add content
5. Verify that the width you have set in the theme settings is being used on each layout
6. Change the theming width settings to full width
7. View the page again
8. Optionally, change the section margin settings to "Section Margin: Full Width Container"

**Comment by mark-bennett-uiowa** [comment]
#191 works as suggested above.

**Comment by bspeare** [comment]
@pyrello Just outer margin?  Since full width is an edge-case scenario I would probably suggest using the layout builder styles to add padding to the left and right of the container.   How do you want it to behave?

**Comment by pyrello** [comment]
@bspeare Maybe I am missing something here, but I think that if you select with full or fixed width (regardless of which one is the preferred methodology) they should both have default behavior that makes sense out of the box. I would expect, after setting the theme width setting to full width, that pages would, by default, have a standard margin along the edge. I'm not sure what that standard margin would be, but I'm sure if you were building a full width site, you would not choose to have no outer margin.

**Comment by pyrello** [comment]
#188 seems good
#163 is probably okay, but it seems I'll need to open another issue to discuss default settings for fixed width option
#162 also is working now, with same caveats as #163

**Comment by pyrello** [comment]
Also #190 and #191 appear to be good.

**Comment by mark-bennett-uiowa** [comment]
How about adding an image for the collegiate theme? Here is a quick one I whipped up.
screenshot

**Comment by pyrello** [comment]
I believe that all of these pass in terms of how they are described. I have added questions to the relevant issues where I'm not clear on the intention or think more conversation is required.

**Pull request merged**
