### PR TITLE
Feature: Replace Lightning Media with custom-built components

### PR DESCRIPTION
**Pull request by pyrello**
Finally...

This feature allows us to be able to remove Lightning components by replacing the elements that we were depending on for other custom modules or the collegiate_basic profile. For better or worse, this is a fairly big change and testing it is a bit tricky.

Some things to note:
* This update doesn't actually remove the Lightning components, yet. That will come after in a separate feature.
* Instead, this creates media components to replace the ones provided by Lightning and swaps those out in the collegiate_basic profile.
* To make it easier to do a side-by-side comparison, I created a clone of collegiate_basic - called collegiate_basic_old - which can be used to do a site install for another site in case you want to see what the settings or UI were like before the change.
* After we have tested this PR, I will remove the collegiate_basic_old profile and push a new commit.

# Tests

## 1. Installation
`drush @theming.local si collegiate_basic` to ensure no issues with installation.

## 2. Check the media types
Confirm that all media types are present after installation: Document, Image, Video, Remote Video.

## 3. Test block types
* Create a basic page piece of content and edit in layout builder. 
* Add all the block types provided by uiowa_lb_blocks.
* Confirm that media fields work as expected.

## 4. Test media fields on entity_types_* content types
* Install each entity_types_* module.
* Create a piece of content for each content type.
* Confirm that media fields work as expected.

## 5. Test a multi-media field
* Create a new media field on the basic page content type.
* _Note:_ When creating the media field, you may get a big red error message. Feel free to document - this is a known issue that I'm hoping is fixed by updating the Drupal core version later.
* Select at least the Image, Video, and Remote Video media types and save the field settings.
* Create a piece of basic page content and use the new field.
* Confirm that each media type widget works as expected.

### CODE REVIEW

**Comment by pyrello** [comment]
When testing the uiowa_lb_blocks block types and the media integration, I'm noticing that the media_library modal widget looks kind of messed up when accessed via layout builder (and therefore via collegiate_theme). Looks like we need to add some styling to make that look prettier. Issue added: #205 

Also, there appears to be an extra button and I'm not sure why it shows up or what it is supposed to do:
Screen Shot 2019-11-14 at 6 56 28 AM

It doesn't seem to have any affect when I click it.

**Comment by bspeare** [comment]
When testing uploading an image into the Body area, I get this error that prevents me from embedding an image:

Screen Shot 2019-11-14 at 10 08 43 AM

**Comment by pyrello** [comment]
@bspeare Do you think it is worth figuring that issue out? Or just plowing ahead towards 8.8?

**Comment by pyrello** [comment]
I'm adding this as a note from my Slack convo with @bspeare:

There are multiple changes going on:

Removing all Lightning modules
Implementing new media config
Switching new media config to use built-in Media Library widget instead of Entity/Media browser
Switching new media config to use core oembed field instead of contrib (video_embed_field)
I’ve modeled the new media config after the core config provided by the standard install profile
Which uses all the new core-based stuff
So, it seems I just need to figure out what is still not configured right related to uiowa_lb_blocks
I tried adding a media field to the basic block content type similar to the image field on other uiowa block types and exported it via features to compare the config to the uiowa blocks config
I don’t see what is different

**Comment by pyrello** [comment]
The patch seems to have fixed all the weirdness that we were seeing (except anything related to WYSIWYG).

I have tested all the block types and they work as expected. Entity type modules install correctly, although I haven't tested their media fields yet.

**Comment by pyrello** [comment]
So, the main thing that we need to figure out at this point is whether you want me to fix the WYSIWYG stuff or you are okay with leaving it broken until we get updated to 8.8.x

**Comment by bspeare** [comment]
I think we can wait until 8.8.x to fix the WYSIWYG stuff.

**Pull request merged**
