### PR TITLE
Feature: Fix the drag and drop functionality custom blocks

### PR DESCRIPTION
**Pull request by bspeare**
Initial work on issue #231 

# How to Test

1. `drush @theming.local si collegiate`
2. Add a basic page
3. Edit basic page layout
4. Create multiple sections
5. Add a card, banner, statistic, and feature component
6. Try to drag them around and save the page
7. Verify that saved page reflects the changes that you made

### CODE REVIEW

**Comment by pyrello** [comment]
Most immediately, I am noticing that this line doesn't seem to be working correctly, as it is printing out all the attributes and not just the classes:

https://github.com/uiowa/uiowa01/pull/234/files#diff-457621abf5e59d4f88b2504f0d012388R48

Screen Shot 2019-11-26 at 3 27 35 PM

I think the line should instead be:
```
      "card_classes": attributes.addclass(classes)['class'],
```
And that would apply for all the comparable lines.

Also, its not exactly related to this PR, but I just noticed this:
https://github.com/uiowa/uiowa01/blob/93071de7934a4357197617b3decb51158a9167b7/docroot/themes/custom/collegiate_theme/templates/block/block--inline-block--uiowa-banner.html.twig#L74

And I am wondering what the purpose of outputting that image there is. I have more thoughts about the way this is structured, but I'll save those for a follow-up message.

**Comment by bspeare** [comment]
@pyrello The twig line that you referenced above is for outputting the responsive image tags from Drupal.   As you can see here https://github.com/uiowa/uiowa01/blob/4a4fd316b53231867923e4980337ddc03e041b1a/docroot/themes/custom/collegiate_theme/templates/block/block--inline-block--uiowa-card.html.twig#L57, the template is using Twig Embed (https://twig.symfony.com/doc/2.x/tags/embed.html) to swap in the responsive images from Drupal.

**Comment by pyrello** [comment]
I ran into some more issues with when testing this, specifically with the card component. At first it seemed clear there was a logical error in the template when looking at these two sections:

https://github.com/uiowa/uiowa01/blob/4a4fd316b53231867923e4980337ddc03e041b1a/docroot/themes/custom/collegiate_theme/templates/block/block--inline-block--uiowa-card.html.twig#L41-L43

https://github.com/uiowa/uiowa01/blob/4a4fd316b53231867923e4980337ddc03e041b1a/docroot/themes/custom/collegiate_theme/templates/block/block--inline-block--uiowa-card.html.twig#L61-L66

The lack of the if/else/endif construct in the first section seems like it will create problems.

Additionally, I'm not sure that it is possible to nest an `<a>` tag inside another <a> tag: https://stackoverflow.com/a/1828032

I tried fixing the above issue by changing the code to:
```
        {% block card_wrapper_start %}
          {% if content.field_uiowa_card_link[0]['#url'] is not empty %}
            <a href="{{ card_link_url }}" class="card card__{{ card_position }} {{ card_classes }}{{ attributes ? attributes.class }}"{{ attributes ? attributes|without('class') }}>
          {% else %}
            <div class="card card__{{ card_position }} {{ card_classes }}{{ attributes ? attributes.class }}"{{ attributes ? attributes|without('class') }}>
          {% endif %}
        {% endblock %}
```

But that seemed to cause the buttons to be pushed outside of the component:
Screen Shot 2019-11-27 at 2 53 12 PM

So, I am wondering if we need to remove the inner `<a>` element when we are wrapping the entire component in an `<a>` tag, possibly replacing it with a `<button>` element instead?

**Comment by bspeare** [comment]
Thanks for finding that.  I meant to remove all of the <a> tag wrappers and just put the link on the card button instead.

**Pull request merged**
