### PR TITLE
Convert collegiate_theme to use embedded version of UDS

### PR DESCRIPTION
**Pull request by pyrello**

### CODE REVIEW

**Comment by pyrello** [comment]
@bspeare I think I have all the scss files updated for this. Since the twigs all use references that are defined in collegiate_theme.info.yml, I think all I needed to do was update those locations.

Still getting a gulp build error:
```console
uds/components/superfish/_superfish.scss
Error: Undefined variable: "$fa-var-bars".
        on line 78 of uds/components/superfish/_superfish.scss
        from line 6 of scss/components/superfish/superfish.scss
>>       content: fa-content($fa-var-bars);

   --------------------------^
```

I'm assuming this might be something you have already fixed in a newer version of UDS?

**Comment by bspeare** [comment]
It looks like the @import needs to be fixed for a few files which is causing the error above.   I will work on fixing that now.

**Comment by bspeare** [comment]
Also, is it your intent to use the components and assets folders within uds instead of the dist/scss/uds_components files?

**Comment by pyrello** [comment]
I wrote it that way because it was more straightforward in my mind. However, I'm not opposed to rewriting to use stuff from the dist folder.

**Comment by bspeare** [comment]
That's great, it is more straightforward.  I can get rid of the gulp function in uds that creates that extra folder.   I just have a few small fixes and then I will push it up.

**Comment by pyrello** [comment]
Sounds good. Thanks!

**Pull request merged**
