### PR TITLE
Feature: Add HDS search / Remove additional header alignment options

### PR DESCRIPTION
**Pull request by bspeare**
Work on issues #312 and #306.

# How to test

1. `drush @theming.local si collegiate`
2. Verify that site install has 'site name left, menu left' 
3. Enable uiowa_book module
4. Go to a-z list page and verify HDS styles are applied: https://theming.uiowa.local.site/a-z
5. Add views exposed search block to page with layout builder enabled and verify that styles are there
6. Let me know if you have any feedback on https://github.com/uiowa/uiowa01/pull/315#issuecomment-572709647

### CODE REVIEW

**Comment by bspeare** [comment]
@pyrello and @mark-bennett-uiowa, what other search forms do we need to add here: https://github.com/uiowa/uiowa01/blob/c99a894db9cecf7108f0ea38a671b888d7ee2c5d/docroot/themes/custom/collegiate_theme/collegiate_theme.theme#L93?

For example, the A-Z list has form id `views-exposed-form_book-toc-page-book-atoz` - is there a better way to add this form_alter so that it covers all the search forms generated by Drupal?

**Comment by pyrello** [comment]
@bspeare It seems like we should be able to catch all views exposed forms somehow, although I'm not sure off the top of my head what that would be. I found this example: https://drupal.stackexchange.com/a/280642/6066; But it seems unlikely that all of those forms have the `$form_id == 'views_exposed_form'`.

**Comment by pyrello** [comment]
According to this gist (https://gist.github.com/jez500/4d1ef061e41f69a964732461cb0ec43a), it seems like you could use a check for `$form['#id'] == 'views_exposed_form'`.

**Comment by bspeare** [comment]
@pyrello , Thanks!  I will try that.

**Comment by bspeare** [comment]
I'm having the same issue described here: https://drupal.stackexchange.com/questions/247136/add-a-class-the-the-form-element-tag-of-the-search-block-form.   Do you guys have any suggestions on adding classes to the search form? 

`function collegiate_theme_form_alter(&$form, $form_state, $form_id) {
  if (strpos($form_id, 'search_block_form') !== FALSE) {
    $form['#attributes']['class'][] = 'hds-content hds-search';
  }
}`

The above code will only add classes to the containing div of the form and not the <form> itself.

**Comment by bspeare** [comment]
We are going to need the patch listed on https://github.com/uiowa/uiowa01/issues/217 if @mark-bennett-uiowa wants to place a search form within layout builder.

**Pull request closed without merging**
