### PR TITLE
Fixed #288: Fix small omissions in uiowa_book module.

### LINKED ISSUE #288: Fix small omissions in uiowa_book module
1: Add text to What's New header.
2: A-Z List page in Main Menu by default.
3: Reorder pages in Main Menu.

### PR DESCRIPTION
**Pull request by mark-bennett-uiowa**
These are all minor changes to the uiowa_book module that I noticed during setup of a new site. Does not truly need testing, but a quick glance at the code changes might work best.

### CODE REVIEW

**Comment by mark-bennett-uiowa** [comment]
Im going to push this as its so small. I have checked through the code above and nothing is out of the ordinary.

**Comment by pyrello** [comment]
I guess my only piece of feedback on these changes are that you have included some policy-site-specific content into the view. It makes me wonder if this whole module is somewhat specific to the policy site and should be re-named and placed inside the `docroot/sites/policy.clas.uiowa.edu/modules` directory?

**Comment by mark-bennett-uiowa** [comment]
We can remove the addition in the view description, as Im not exactly thrilled (nor needing that) anyways. The others I vote to keep, and I vote to keep the module outside of the policy modules. It doesnt need to be there, so I can remove the policy specific stuff.

**Comment by pyrello** [comment]
@mark-bennett-uiowa So, to be clear, you think it is likely that you are going to set up multiple sites that need modifications to the book module that are in line with what you have set up in `uiowa_book`?

**Comment by mark-bennett-uiowa** [comment]
I feel that the alterations are to help the book module work better for any of these types of sites (policy or not). It just happens to be a policy site that we are using it for first, and I was probably overzealous on the addition of the view page header that included policy specific text.

**Pull request merged**
